diagrammi uml server
StefanoBavaro/Progetto-MAP pull request #24
Opened 2021-09-09 16:20 UTC by jacopodabramo

Ho aggiunto la cartella docs  con i diagrammi delle classi del server. Non ho realizzato ancora quello totale in quanto voglio prima essere sicuro che questi siano corretti per procedere. Fate una review molto minuziosa
Closes #13

2021-09-09 16:58 UTC, LorenzoCassano requested changes
Innanzitutto per questione stilistiche il nome della cartella dovrebbe essere _doc_ e non _docs_.
Sempre per questione di stile il nome delle cartelle dovrebbero essere scritti tutto in minuscolo(_es_ cartella) e anche i nomi dei file.
Per i file UML ci sono questi problemi:
- Per il package **Data**:
    - La classe attributo non è rappresentata come classe astratta (il nome dovrebbe essere scritto in corsivo)
    -  Sia la classe **ContinuosAttribute**  e **DiscreteAttribute** implementano il **Serializable** ma questo non è segnato nell'UML, è stata una svista oppure è stata fatto volutamente visto che già la superclasse implementa il Serializable?
- Per il package **Mining**:
    - il metodo carica sia in **EmergingPatternMiner** che in **FrequentPatternMiner** deve essere indicato come metodo di classe (deve essere sottolineato)
    - La classe **Item** deve essere indicata come astratta e anche il metodo **checkItemCondition** deve essere indicato come metodo astratto
    - **ContinuosItem** e **DiscretItem**  implementano l'interfaccia **Serializable** ma non è indicato nell'UML (stessa domanda di prima).
- Per il package **Server**:
    - La classe **MultiServer** non estende la classe Thread (invece nell'UML viene detto il contrario)
    - La classe **ServerOneClient** estende la classe Thread ma questo non vi è indicato nell'UML

Cancella i file con estenzione .io

2021-09-09 18:36 UTC, LorenzoCassano approved these changes

2021-09-10 16:01 UTC, StefanoBavaro requested changes
PACKAGE DATA:
I quadrati delle classi Data, EmptySetException, DiscreteAttribute e ContinousAttributeIterator sono troppo piccoli (tagliano alcune signature).
Per alcuni attributi/metodi manca lo spazio tra visibilità e nome del metodo.
Non si vede bene se la classe Attribute è astratta (se si può è meglio accentuare un po' il corsivo).
Meglio sostituire le interfacce presenti con dei cerchi. Cito dalle slide "Nella sua rappresentazione più generale, un’interfaccia è rappresentata
mediante l’utilizzo di un cerchio, sopprimendo la visualizzazione delle
operazioni. Tuttavia, se lo si ritiene importante per la comprensione del
modello, è possibile modellare un’interfaccia come una classe
stereotipata" (Slide 71 del pacchetto programmazione OO).
Manca la visibilità a EmptySetException.
Domanda da fare alla prof: ma, per esempio, nell'uml dobbiamo indicare che EmptySetException estende Exception?
Per l'interfaccia Iterable, è meglio lasciare la classe stereotipata ma in alto a destra metti il simbolo di classe generica con Float. Per iterator invece, siccome non si può mettere il simbolo di classe generica con Float con il cerchio, sostituire il cerchio con la classe stereotipata. Ho comunque un dubbio, che dovremo chiedere alla prof: noi da continuousAttribute facciamo uscire una freccia che indica che indica la relazione di dipendenza con Iterator (che secondo me ci sta perchè un metodo restituisce un oggetto Iterator) e allo stesso tempo però diciamo con la freccia <<create>> che la classe crea istanze di ContinousAttributeIterator, che implementa Iterator: temo sia una ridondanza, meglio chiedere.

2021-09-12 10:05 UTC, jacopodabramo reviewed
Ho preferito non inserire per le due sottoclassi DiscreteItem e ContinuosItem la relazione con Serializable perche è gia esplicata nella superclasse

2021-09-13 08:25 UTC, StefanoBavaro approved these changes

2021-09-20 09:29 UTC, closed without merging